### ISSUE TITLE
Path for /dist/vendor 

### ISSUE THREAD

**Issue by BobTB** [standardnotes/code-editor#1]
I had it hosted on https://test.com/editors/code-editor and highlighting did not work.
I had to move /dist/vendor folder to https://test.com/dist/vendor for it to work. Path is somehow wrong. Of course after this change it works.

![image](https://user-images.githubusercontent.com/15887688/33521622-cd7a5664-d7d7-11e7-8eed-7fdc52800244.png)

**Comment by jackietheripper** [comment]
Hi Bob,
You have to change https://github.com/sn-extensions/code-editor/blob/07fbc4021e18e2ee90ea389100027852db3d3261/index.html#L10 to the right path or the easiest way: Just leave out the slash in front.

Maybe the author of this package can also change this, so that it gets easier to use for those ones who are trying to self-host it.

Regards,
Jelko
